### ISSUE TITLE
Coloring of python functions works only partially

### ISSUE THREAD

**Issue by yoflippo** [0b5vr/vscode-monokai-sharp#1]
![screenshot from 2019-03-07 12-20-40](https://user-images.githubusercontent.com/13065538/53953379-7b27e500-40d3-11e9-9385-fc07dfa05f2a.png)

The screenshot shows the enity.py file from the home assistant project.

**Comment by 0b5vr** [comment]
Thank you for reporting! I think I can address to it later

**Comment by 0b5vr** [comment]
You said the issue is happening on this source code, right?

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/entity.py

The issue doesn't repro on my env

![image](https://user-images.githubusercontent.com/7824814/54472312-b9c34b00-4809-11e9-9e91-ce6ac940b727.png)

How it looks like in original Monokai?

**Comment by yoflippo** [comment]
Yes, and I confirmed that it is working on W10 and Ubuntu. Must be some other faulty exentension then. Thanks for your time.

**Comment by 0b5vr** [comment]
Oh
